tag: unet_pl_batch_8
seed: 77
sample_len: 16384
data:
  dataset_train:
    file_path:  '/home/dev/other/denois/train.txt'
    mode: 'train'

  dataset_val:
    file_path: '/home/dev/other/denois/val.txt'
    mode: 'validation'

  loader_train:
    shuffle: True
    num_workers: 2
    batch_size: 8

model:
  n_layers: 12
  channels_interval:  24

optim:
  lr: 0.0001

loss: mse_loss # l1_lossw

trainer:
  sample_rate: 16000  #16000
  resume: False # continue training
  epochs: 1200
  visualize_waveform_limit: 5
  visualize_audio_limit: 5
  visualize_spectrogram_limit: 5
  validation_interval: 0.1
  sample_length: 16384
  base_dir: '../results/'
  spectro_dir: 'speech'
  exp_name: unet_pl_test
  cudnn_deterministic: True
