tag: unet
seed: 77
data:
  dataset_train:
    file_path:  '/home/dev/other/denois/Denoising/files.txt'
    sample_length: 16384
    mode: 'train'

  dataset_val:
    file_path: '/home/dev/other/denois/Denoising/files.txt'
    sample_length: 16384
    mode: 'validation'

  loader_train:
    shuffle: True
    num_workers: 2
    batch_size: 64

model:
  n_layers: 12
  channels_interval:  24

optim:
  lr: 0.001
  beta1: 0.9
  beta2: 0.009

loss: mse_loss # l1_lossw

trainer:
  resume: False # continue training
  epochs: 1200
  save_checkpoint_interval: 10
  find_max: True  # early stop - save best model but keep training
  val_interval: 10
  visualize_waveform_limit: 20
  visualize_spectrogram_limit: 20
  validation_interval: 1
  sample_length: 16384
  root_dir: 'outputs'
  exp_name: debug
  cudnn_deterministic: True
